export const integrationCategories = {
  "crm-sales": { label: "💼 CRM & Sales", count: 45 },
  communication: { label: "💬 Communication", count: 35 },
  finance: { label: "💰 Finance & Accounting", count: 25 },
  marketing: { label: "📈 Marketing", count: 40 },
  productivity: { label: "⚡ Productivity", count: 50 },
  ecommerce: { label: "🛒 E-commerce", count: 30 },
  "ai-data": { label: "🤖 AI & Analytics", count: 25 },
  storage: { label: "☁️ Storage & Files", count: 20 },
  social: { label: "📱 Social Media", count: 15 },
  custom: { label: "🔧 Custom APIs", count: "∞" },
}

export const integrations = {
  "crm-sales": [
    {
      name: "HubSpot",
      icon: "🏢",
      popularity: "high",
      description: "Complete CRM with lead scoring, deal tracking, and email automation",
    },
    {
      name: "Salesforce",
      icon: "⚡",
      popularity: "high",
      description: "Enterprise CRM with advanced pipeline management",
    },
    { name: "Pipedrive", icon: "📊", popularity: "high", description: "Visual sales pipeline management" },
    { name: "Zoho CRM", icon: "🎯", popularity: "medium", description: "All-in-one customer relationship management" },
    { name: "Freshsales", icon: "🌿", popularity: "medium", description: "Modern CRM with built-in phone and email" },
    { name: "ActiveCampaign", icon: "📧", popularity: "high", description: "Email marketing with CRM capabilities" },
    { name: "Copper", icon: "🔶", popularity: "medium", description: "CRM designed for Google Workspace" },
    { name: "Airtable", icon: "📋", popularity: "high", description: "Spreadsheet-database hybrid for lead tracking" },
    { name: "Notion", icon: "📝", popularity: "high", description: "All-in-one workspace for sales documentation" },
    { name: "ClickUp", icon: "✅", popularity: "high", description: "Project management with CRM features" },
    { name: "Monday.com", icon: "🗓️", popularity: "high", description: "Work OS for sales team collaboration" },
    { name: "Intercom", icon: "💬", popularity: "high", description: "Customer messaging and support platform" },
    { name: "Zendesk", icon: "🎫", popularity: "high", description: "Customer service and ticketing system" },
    { name: "Calendly", icon: "📅", popularity: "high", description: "Automated meeting scheduling" },
    { name: "Typeform", icon: "📋", popularity: "high", description: "Interactive forms and surveys" },
  ],
  communication: [
    { name: "Slack", icon: "💬", popularity: "high", description: "Team messaging and collaboration hub" },
    { name: "Microsoft Teams", icon: "👥", popularity: "high", description: "Video conferencing and team chat" },
    { name: "Discord", icon: "🎮", popularity: "high", description: "Voice, video, and text communication" },
    { name: "Gmail", icon: "📧", popularity: "high", description: "Email with advanced automation" },
    { name: "Outlook", icon: "📮", popularity: "high", description: "Microsoft email and calendar" },
    { name: "Twilio", icon: "📱", popularity: "high", description: "SMS, voice, and video APIs" },
    { name: "Zoom", icon: "📹", popularity: "high", description: "Video conferencing and webinars" },
  ],
  finance: [
    { name: "QuickBooks", icon: "💰", popularity: "high", description: "Small business accounting software" },
    { name: "Xero", icon: "💙", popularity: "high", description: "Cloud-based accounting platform" },
    { name: "Stripe", icon: "💳", popularity: "high", description: "Online payment processing" },
    { name: "PayPal", icon: "💙", popularity: "high", description: "Digital payments platform" },
  ],
  marketing: [
    { name: "Google Analytics", icon: "📊", popularity: "high", description: "Website traffic and behavior analysis" },
    { name: "Google Ads", icon: "🎯", popularity: "high", description: "Online advertising platform" },
    { name: "Facebook Ads", icon: "📘", popularity: "high", description: "Social media advertising" },
    { name: "Mailchimp", icon: "🐵", popularity: "high", description: "Email marketing automation" },
    { name: "Klaviyo", icon: "🎹", popularity: "high", description: "E-commerce email and SMS marketing" },
  ],
  productivity: [
    {
      name: "Google Workspace",
      icon: "🌈",
      popularity: "high",
      description: "Gmail, Drive, Docs, Sheets, Calendar suite",
    },
    { name: "Microsoft 365", icon: "🟦", popularity: "high", description: "Office apps and cloud services" },
    { name: "Notion", icon: "📝", popularity: "high", description: "All-in-one workspace for notes and docs" },
    { name: "Airtable", icon: "📋", popularity: "high", description: "Spreadsheet-database hybrid" },
    { name: "Trello", icon: "📌", popularity: "high", description: "Visual project management boards" },
    { name: "Asana", icon: "✅", popularity: "high", description: "Team project and task management" },
    { name: "Monday.com", icon: "🗓️", popularity: "high", description: "Work operating system" },
    { name: "ClickUp", icon: "✅", popularity: "high", description: "All-in-one productivity suite" },
  ],
  ecommerce: [
    { name: "Shopify", icon: "🛍️", popularity: "high", description: "Leading e-commerce platform" },
    { name: "WooCommerce", icon: "🛒", popularity: "high", description: "WordPress e-commerce plugin" },
    { name: "Magento", icon: "🔶", popularity: "medium", description: "Open source e-commerce platform" },
    { name: "BigCommerce", icon: "🏪", popularity: "medium", description: "Enterprise e-commerce solution" },
    { name: "Amazon Seller Central", icon: "📦", popularity: "high", description: "Amazon marketplace management" },
  ],
  "ai-data": [
    { name: "OpenAI", icon: "🤖", popularity: "high", description: "GPT models for text and image generation" },
    {
      name: "Anthropic Claude",
      icon: "🧠",
      popularity: "medium",
      description: "AI assistant for conversations and analysis",
    },
    { name: "Google AI", icon: "🌈", popularity: "medium", description: "Machine learning and AI services" },
    { name: "Hugging Face", icon: "🤗", popularity: "medium", description: "Open source AI model platform" },
    { name: "Snowflake", icon: "❄️", popularity: "medium", description: "Cloud data warehouse" },
  ],
  storage: [
    { name: "Google Drive", icon: "💾", popularity: "high", description: "Cloud storage and file sharing" },
    { name: "Dropbox", icon: "📦", popularity: "high", description: "Cloud storage and collaboration" },
    { name: "OneDrive", icon: "☁️", popularity: "high", description: "Microsoft cloud storage" },
    { name: "Amazon S3", icon: "🪣", popularity: "high", description: "Object storage service" },
  ],
  social: [
    { name: "Facebook", icon: "📘", popularity: "high", description: "Social networking and business pages" },
    { name: "Instagram", icon: "📸", popularity: "high", description: "Photo and video sharing" },
    { name: "Twitter/X", icon: "🐦", popularity: "high", description: "Microblogging and social networking" },
    { name: "LinkedIn", icon: "💼", popularity: "high", description: "Professional networking" },
    { name: "YouTube", icon: "📺", popularity: "high", description: "Video sharing platform" },
  ],
  custom: [
    { name: "HTTP Request", icon: "🌐", popularity: "high", description: "Connect to any REST API endpoint" },
    { name: "Webhooks", icon: "🪝", popularity: "high", description: "Real-time HTTP callbacks" },
    { name: "GraphQL", icon: "🔗", popularity: "medium", description: "Query language for APIs" },
    { name: "Custom Python", icon: "🐍", popularity: "high", description: "Execute custom Python code" },
    { name: "Custom JavaScript", icon: "📜", popularity: "high", description: "Run custom JavaScript functions" },
  ],
}
