export const integrationData: Record<string, { name: string; description: string; domain: string }> = {
  advbox: { name: "ADVBOX", description: "Legal software for lawyers", domain: "advbox.com.br" },
  actionnetwork: { name: "Action Network", description: "Digital organizing tools", domain: "actionnetwork.org" },
  activecampaign: { name: "ActiveCampaign", description: "Email marketing and automation", domain: "activecampaign.com" },
  adalo: { name: "Adalo", description: "No-code app builder", domain: "adalo.com" },
  affinity: { name: "Affinity", description: "Relationship intelligence platform", domain: "affinity.co" },
  agilecrm: { name: "Agile CRM", description: "All-in-one CRM for small businesses", domain: "agilecrm.com" },
  airbyte: { name: "Airbyte", description: "Open-source data integration", domain: "airbyte.com" },
  airtable: { name: "Airtable", description: "Spreadsheet-database hybrid", domain: "airtable.com" },
  airtop: { name: "Airtop", description: "AI-powered business management", domain: "airtop.ai" },
  amqpsender: { name: "AMQP Sender", description: "Message queuing protocol", domain: "amqp.org" },
  anthropic: { name: "Anthropic", description: "AI safety and research", domain: "anthropic.com" },
  apitemplateio: { name: "APITemplate.io", description: "Automated PDF and image generation", domain: "apitemplate.io" },
  appflowy: { name: "AppFlowy", description: "Open-source Notion alternative", domain: "appflowy.io" },
  asaas: { name: "Asaas", description: "Financial management platform", domain: "asaas.com" },
  asana: { name: "Asana", description: "Work management platform", domain: "asana.com" },
  awscognito: { name: "AWS Cognito", description: "Identity and access management", domain: "aws.amazon.com" },
  awscomprehend: { name: "AWS Comprehend", description: "Natural language processing", domain: "aws.amazon.com" },
  awsdynamodb: { name: "AWS DynamoDB", description: "NoSQL database service", domain: "aws.amazon.com" },
  awselasticloadbalancing: { name: "AWS Elastic Load Balancing", description: "Distribute incoming application traffic", domain: "aws.amazon.com" },
  awslambda: { name: "AWS Lambda", description: "Serverless compute service", domain: "aws.amazon.com" },
  awsrekognition: { name: "AWS Rekognition", description: "Image and video analysis", domain: "aws.amazon.com" },
  awss3: { name: "AWS S3", description: "Object storage service", domain: "aws.amazon.com" },
  awsses: { name: "AWS SES", description: "Email sending and receiving service", domain: "aws.amazon.com" },
  awssns: { name: "AWS SNS", description: "Pub/sub messaging service", domain: "aws.amazon.com" },
  awssqs: { name: "AWS SQS", description: "Message queuing service", domain: "aws.amazon.com" },
  awstextract: { name: "AWS Textract", description: "Extract text and data from documents", domain: "aws.amazon.com" },
  awstranscribe: { name: "AWS Transcribe", description: "Automatic speech recognition", domain: "aws.amazon.com" },
  azurecosmosdb: { name: "Azure Cosmos DB", description: "NoSQL and relational database", domain: "azure.microsoft.com" },
  azureopenai: { name: "Azure OpenAI", description: "AI models for various applications", domain: "azure.microsoft.com" },
  azurestorage: { name: "Azure Storage", description: "Cloud storage for modern applications", domain: "azure.microsoft.com" },
  bamboohr: { name: "BambooHR", description: "HR software for small and medium businesses", domain: "bamboohr.com" },
  bankerize: { name: "Bankerize", description: "Financial services platform", domain: "bankerize.com.br" },
  bannerbear: { name: "Bannerbear", description: "Automated image and video generation", domain: "bannerbear.com" },
  baserow: { name: "Baserow", description: "Open-source no-code database", domain: "baserow.io" },
  beeminder: { name: "Beeminder", description: "Goal tracking with a sting", domain: "beeminder.com" },
  bitly: { name: "Bitly", description: "URL shortening service", domain: "bitly.com" },
  bitrix24: { name: "Bitrix24", description: "Collaboration and CRM platform", domain: "bitrix24.com" },
  box: { name: "Box", description: "Cloud content management", domain: "box.com" },
  brandfetch: { name: "Brandfetch", description: "Brand asset retrieval", domain: "brandfetch.com" },
  bravesearch: { name: "Brave Search", description: "Private search engine", domain: "brave.com" },
  brevo: { name: "Brevo", description: "All-in-one marketing platform", domain: "brevo.com" },
  bubble: { name: "Bubble", description: "No-code web app builder", domain: "bubble.io" },
  calculator: { name: "Calculator", description: "Perform calculations", domain: "n8n.io" },
  calcom: { name: "Cal.com", description: "Scheduling infrastructure for everyone", domain: "cal.com" },
  carbonejs: { name: "Carbone JS", description: "Report generation from JSON data", domain: "carbone.io" },
  clearbit: { name: "Clearbit", description: "B2B marketing intelligence", domain: "clearbit.com" },
  clickup: { name: "ClickUp", description: "All-in-one productivity platform", domain: "clickup.com" },
  cloudconvert: { name: "CloudConvert", description: "Online file converter", domain: "cloudconvert.com" },
  cloudflare: { name: "Cloudflare", description: "Web performance and security", domain: "cloudflare.com" },
  cnjplookup: { name: "CNPJ Lookup", description: "Brazilian company information", domain: "receitaws.com.br" },
  coingecko: { name: "CoinGecko", description: "Cryptocurrency data and analytics", domain: "coingecko.com" },
  comerciaio: { name: "Comercia.io", description: "E-commerce platform", domain: "comercia.io" },
  convertapi: { name: "ConvertAPI", description: "File conversion API", domain: "convertapi.com" },
  convertkit: { name: "ConvertKit", description: "Email marketing for creators", domain: "convertkit.com" },
  copper: { name: "Copper", description: "CRM for Google Workspace", domain: "copper.com" },
  cortex: { name: "Cortex", description: "Internal developer portal", domain: "cortex.io" },
  crawler: { name: "Crawler (FireCrawl)", description: "Web crawling and data extraction", domain: "firecrawl.dev" },
  crmgestorclientes: { name: "CRM (GestorClientes)", description: "Customer management system", domain: "gestorclientes.com" },
  customerdatastore: { name: "Customer Datastore", description: "Store and retrieve customer data", domain: "n8n.io" },
  customermessenger: { name: "Customer Messenger", description: "Send messages to customers", domain: "n8n.io" },
  customerio: { name: "Customer.io", description: "Customer engagement platform", domain: "customer.io" },
  datetime: { name: "Date & Time", description: "Work with dates and times", domain: "n8n.io" },
  deepl: { name: "DeepL", description: "AI-powered translation", domain: "deepl.com" },
  deepseek: { name: "DeepSeek", description: "AI research and development", domain: "deepseek.com" },
  demio: { name: "Demio", description: "Webinar platform for marketers", domain: "demio.com" },
  discord: { name: "Discord", description: "Communication platform for communities", domain: "discord.com" },
  discourse: { name: "Discourse", description: "Open-source discussion platform", domain: "discourse.org" },
  disqus: { name: "Disqus", description: "Community engagement platform", domain: "disqus.com" },
  duckdb: { name: "DuckDB", description: "In-process SQL OLAP database", domain: "duckdb.org" },
  dropbox: { name: "Dropbox", description: "File hosting service", domain: "dropbox.com" },
  dropcontact: { name: "Dropcontact", description: "Email enrichment and verification", domain: "dropcontact.com" },
  egoi: { name: "E-goi", description: "Multichannel marketing automation", domain: "e-goi.com" },
  editimage: { name: "Edit Image", description: "Modify and transform images", domain: "n8n.io" },
  editimageplus: { name: "Edit Image Plus", description: "Advanced image editing", domain: "n8n.io" },
  elasticsearch: { name: "Elasticsearch", description: "Distributed search and analytics engine", domain: "elastic.co" },
  elasticsecurity: { name: "Elastic Security", description: "SIEM and endpoint security", domain: "elastic.co" },
  emelia: { name: "Emelia", description: "Cold email outreach platform", domain: "emelia.io" },
  erpnext: { name: "ERPNext", description: "Open-source ERP software", domain: "erpnext.com" },
  evolutionapi: { name: "Evolution API (WhatsApp)", description: "WhatsApp Business API", domain: "evolution-api.com" },
  executiondata: { name: "Execution Data", description: "Access data from previous nodes", domain: "n8n.io" },
  extractfromfile: { name: "Extract From File", description: "Extract text and data from files", domain: "n8n.io" },
  facebookgraphapi: { name: "Facebook Graph API", description: "Access Facebook's social graph", domain: "facebook.com" },
  filemaker: { name: "FileMaker", description: "Low-code application development", domain: "filemaker.com" },
  firecrawl: { name: "FireCrawl", description: "Web crawling and data extraction", domain: "firecrawl.dev" },
  flow: { name: "Flow", description: "Project and task tracking", domain: "getflow.com" },
  freshdesk: { name: "Freshdesk", description: "Customer support software", domain: "freshdesk.com" },
  freshservice: { name: "Freshservice", description: "IT service management", domain: "freshservice.com" },
  freshworkscrm: { name: "Freshworks CRM", description: "Sales and marketing CRM", domain: "freshworks.com" },
  ftp: { name: "FTP", description: "File Transfer Protocol", domain: "n8n.io" },
  getresponse: { name: "GetResponse", description: "Email marketing and online campaign management", domain: "getresponse.com" },
  git: { name: "Git", description: "Version control system", domain: "git-scm.com" },
  github: { name: "GitHub", description: "Code hosting and collaboration", domain: "github.com" },
  gitlab: { name: "GitLab", description: "DevOps platform", domain: "gitlab.com" },
  gmail: { name: "Gmail", description: "Email service by Google", domain: "gmail.com" },
  gotowebinar: { name: "GoToWebinar", description: "Webinar and virtual event platform", domain: "goto.com" },
  googleads: { name: "Google Ads", description: "Online advertising platform", domain: "ads.google.com" },
  googleanalytics: { name: "Google Analytics", description: "Web analytics service", domain: "analytics.google.com" },
  googlebigquery: { name: "Google BigQuery", description: "Serverless data warehouse", domain: "cloud.google.com" },
  googlebooks: { name: "Google Books", description: "Search the full text of books", domain: "books.google.com" },
  googlebusinessprofile: { name: "Google Business Profile", description: "Manage your online presence", domain: "business.google.com" },
  googlecalendar: { name: "Google Calendar", description: "Time-management and scheduling", domain: "calendar.google.com" },
  googlecloudfirestore: { name: "Google Cloud Firestore", description: "NoSQL document database", domain: "cloud.google.com" },
  googlecloudnaturallanguage: { name: "Google Cloud Natural Language", description: "Analyze text with machine learning", domain: "cloud.google.com" },
  googlecloudrealtimedatabase: { name: "Google Cloud Realtime Database", description: "NoSQL cloud database", domain: "cloud.google.com" },
  googlecloudstorage: { name: "Google Cloud Storage", description: "Object storage for companies", domain: "cloud.google.com" },
  googlecontacts: { name: "Google Contacts", description: "Contact management tool", domain: "contacts.google.com" },
  googledocs: { name: "Google Docs", description: "Online word processor", domain: "docs.google.com" },
  googledrive: { name: "Google Drive", description: "File storage and synchronization", domain: "drive.google.com" },
  googlegemini: { name: "Google Gemini", description: "Multimodal AI model", domain: "google.com" },
  googleperspective: { name: "Google Perspective", description: "API for detecting toxic comments", domain: "perspectiveapi.com" },
  googlesheets: { name: "Google Sheets", description: "Online spreadsheet application", domain: "sheets.google.com" },
  googleslides: { name: "Google Slides", description: "Online presentation application", domain: "slides.google.com" },
  googletasks: { name: "Google Tasks", description: "Task management application", domain: "tasks.google.com" },
  googletranslate: { name: "Google Translate", description: "Multilingual neural machine translation", domain: "translate.google.com" },
  googleworkspaceadmin: { name: "Google Workspace Admin", description: "Manage Google Workspace for your organization", domain: "admin.google.com" },
  grafana: { name: "Grafana", description: "Multi-platform open source analytics", domain: "grafana.com" },
  grist: { name: "Grist", description: "Modern relational spreadsheet", domain: "getgrist.com" },
  hackernews: { name: "Hacker News", description: "Social news website", domain: "news.ycombinator.com" },
  halopsa: { name: "HaloPSA", description: "PSA software for MSPs", domain: "halopsa.com" },
  harvest: { name: "Harvest", description: "Time tracking software", domain: "getharvest.com" },
  helpscout: { name: "Help Scout", description: "Customer service software", domain: "helpscout.com" },
  highlevel: { name: "HighLevel", description: "All-in-one sales and marketing platform", domain: "gohighlevel.com" },
  homeassistant: { name: "Home Assistant", description: "Open source home automation", domain: "home-assistant.io" },
  hotmart: { name: "Hotmart", description: "Platform for digital products", domain: "hotmart.com" },
  hubspot: { name: "HubSpot", description: "CRM, marketing, sales, and service software", domain: "hubspot.com" },
  humanticai: { name: "Humantic AI", description: "AI-powered personality insights", domain: "humantic.ai" },
  hunter: { name: "Hunter", description: "Email finder and verifier", domain: "hunter.io" },
  instagram: { name: "Instagram", description: "Photo and video sharing social network", domain: "instagram.com" },
  integremecnpj: { name: "Integre.me CNPJ", description: "Brazilian company information", domain: "integre.me" },
  intercom: { name: "Intercom", description: "Customer communications platform", domain: "intercom.com" },
  iterable: { name: "Iterable", description: "Cross-channel marketing platform", domain: "iterable.com" },
  jenkins: { name: "Jenkins", description: "Open source automation server", domain: "jenkins.io" },
  jinaai: { name: "Jina AI", description: "Multimodal AI ecosystem", domain: "jina.ai" },
  jirasoftware: { name: "Jira Software", description: "Issue tracking and project management", domain: "atlassian.com" },
  kafka: { name: "Kafka", description: "Distributed event streaming platform", domain: "kafka.apache.org" },
  keap: { name: "Keap", description: "CRM and marketing automation for small business", domain: "keap.com" },
  keitaro: { name: "Keitaro", description: "Tracker for affiliate marketing", domain: "keitaro.io" },
  ldap: { name: "LDAP", description: "Lightweight Directory Access Protocol", domain: "openldap.org" },
  lemlist: { name: "Lemlist", description: "Cold email and sales engagement platform", domain: "lemlist.com" },
  line: { name: "Line", description: "Messaging application", domain: "line.me" },
  linear: { name: "Linear", description: "Issue tracking and project management", domain: "linear.app" },
  lingvanex: { name: "LingvaNex", description: "Translation and dictionary services", domain: "lingvanex.com" },
  linkedin: { name: "LinkedIn", description: "Professional networking service", domain: "linkedin.com" },
  lonescale: { name: "LoneScale", description: "B2B sales intelligence", domain: "lonescale.com" },
  mailchimp: { name: "Mailchimp", description: "Email marketing and automation", domain: "mailchimp.com" },
  mailerlite: { name: "MailerLite", description: "Email marketing and website builder", domain: "mailerlite.com" },
  mailgun: { name: "Mailgun", description: "Email API for developers", domain: "mailgun.com" },
  mailjet: { name: "Mailjet", description: "Email marketing and transactional email", domain: "mailjet.com" },
  mailcheck: { name: "Mailcheck", description: "Email validation service", domain: "mailcheck.co" },
  matrix: { name: "Matrix", description: "Open standard for real-time communication", domain: "matrix.org" },
  mattermost: { name: "Mattermost", description: "Open source collaboration platform", domain: "mattermost.com" },
  mautic: { name: "Mautic", description: "Open source marketing automation", domain: "mautic.org" },
  medium: { name: "Medium", description: "Online publishing platform", domain: "medium.com" },
  merge: { name: "Merge", description: "Unified API for B2B apps", domain: "merge.dev" },
  metabase: { name: "Metabase", description: "Open source business intelligence", domain: "metabase.com" },
  microsoftdynamicscrm: { name: "Microsoft Dynamics CRM", description: "Customer relationship management", domain: "dynamics.microsoft.com" },
  microsoftentraid: { name: "Microsoft Entra ID", description: "Identity and access management", domain: "azure.microsoft.com" },
  microsoftexcel365: { name: "Microsoft Excel 365", description: "Spreadsheet software", domain: "excel.office.com" },
  microsoftgraphsecurity: { name: "Microsoft Graph Security", description: "Unified security API", domain: "microsoft.com" },
  microsoftonedrive: { name: "Microsoft OneDrive", description: "File hosting service", domain: "onedrive.com" },
  microsoftoutlook: { name: "Microsoft Outlook", description: "Personal information manager", domain: "outlook.com" },
  microsoftsql: { name: "Microsoft SQL", description: "Relational database management system", domain: "microsoft.com" },
  microsoftsharepoint: { name: "Microsoft SharePoint", description: "Web-based collaboration platform", domain: "sharepoint.com" },
  microsoftteams: { name: "Microsoft Teams", description: "Business communication platform", domain: "teams.microsoft.com" },
  microsofttodo: { name: "Microsoft To Do", description: "Cloud-based task management", domain: "to-do.office.com" },
  minio: { name: "Minio", description: "High-performance object storage", domain: "min.io" },
  mineru: { name: "Mineru", description: "Data mining and analysis", domain: "n8n.io" },
  mondaycom: { name: "Monday.com", description: "Work operating system", domain: "monday.com" },
  mongodb: { name: "MongoDB", description: "NoSQL database", domain: "mongodb.com" },
  monicacrm: { name: "Monica CRM", description: "Personal relationship management", domain: "monicahq.com" },
  mqtt: { name: "MQTT", description: "Messaging protocol for IoT", domain: "mqtt.org" },
  msg91: { name: "MSG91", description: "Bulk SMS and OTP provider", domain: "msg91.com" },
  mysql: { name: "MySQL", description: "Open-source relational database", domain: "mysql.com" },
  nasa: { name: "NASA", description: "National Aeronautics and Space Administration", domain: "nasa.gov" },
  n8ninternal: { name: "N8N (internal)", description: "Internal n8n functions", domain: "n8n.io" },
  n8nform: { name: "N8N Form", description: "Create forms within n8n", domain: "n8n.io" },
  notion: { name: "Notion", description: "All-in-one workspace", domain: "notion.so" },
  npm: { name: "npm", description: "Package manager for JavaScript", domain: "npmjs.com" },
  nocodb: { name: "NocoDB", description: "Open source Airtable alternative", domain: "nocodb.com" },
  oauth2tinyerp: { name: "OAuth2 (Tiny ERP)", description: "Authentication for Tiny ERP", domain: "tiny.com.br" },
  odoo: { name: "Odoo", description: "Open source business management software", domain: "odoo.com" },
  okta: { name: "Okta", description: "Identity and access management", domain: "okta.com" },
  oneapi: { name: "OneAPI", description: "Unified API for AI models", domain: "solversolutiongroup.com" },
  onesimpleapi: { name: "One Simple API", description: "Collection of useful APIs", domain: "onesimpleapi.com" },
  onfleet: { name: "Onfleet", description: "Last-mile delivery management", domain: "onfleet.com" },
  openai: { name: "OpenAI", description: "AI research and deployment company", domain: "openai.com" },
  openthesaurus: { name: "OpenThesaurus", description: "German thesaurus", domain: "openthesaurus.de" },
  openweathermap: { name: "OpenWeatherMap", description: "Weather data API", domain: "openweathermap.org" },
  oura: { name: "Oura", description: "Smart ring for health tracking", domain: "ouraring.com" },
  paddle: { name: "Paddle", description: "Revenue delivery platform for SaaS", domain: "paddle.com" },
  pagerduty: { name: "PagerDuty", description: "Incident response platform", domain: "pagerduty.com" },
  paypal: { name: "PayPal", description: "Online payments system", domain: "paypal.com" },
  pdfkit: { name: "PDFKit", description: "PDF generation library", domain: "pdfkit.org" },
  peekalink: { name: "Peekalink", description: "Link preview API", domain: "peekalink.io" },
  perplexity: { name: "Perplexity", description: "AI-powered search engine", domain: "perplexity.ai" },
  phantombuster: { name: "PhantomBuster", description: "Code-free automation and data extraction", domain: "phantombuster.com" },
  philipshue: { name: "Philips Hue", description: "Smart lighting system", domain: "meethue.com" },
  pipedrive: { name: "Pipedrive", description: "Sales CRM and pipeline management", domain: "pipedrive.com" },
  plivo: { name: "Plivo", description: "Cloud communication platform", domain: "plivo.com" },
  postbin: { name: "PostBin", description: "Webhook testing tool", domain: "postb.in" },
  posthog: { name: "PostHog", description: "Open source product analytics", domain: "posthog.com" },
  postgres: { name: "Postgres", description: "Open source relational database", domain: "postgresql.org" },
  profitwell: { name: "ProfitWell", description: "Subscription analytics and engagement", domain: "profitwell.com" },
  pushbullet: { name: "Pushbullet", description: "Bridge your devices", domain: "pushbullet.com" },
  pushcut: { name: "Pushcut", description: "Automate iOS with smart notifications", domain: "pushcut.io" },
  pushover: { name: "Pushover", description: "Simple push notifications", domain: "pushover.net" },
  questdb: { name: "QuestDB", description: "High-performance time-series database", domain: "questdb.io" },
  rabbitmq: { name: "RabbitMQ", description: "Open source message broker", domain: "rabbitmq.com" },
  raindrop: { name: "Raindrop", description: "All-in-one bookmark manager", domain: "raindrop.io" },
  randomizer: { name: "Randomizer", description: "Generate random data", domain: "n8n.io" },
  redis: { name: "Redis", description: "In-memory data structure store", domain: "redis.io" },
  rerankercohere: { name: "Reranker Cohere", description: "Semantic search and text ranking", domain: "cohere.com" },
  rssread: { name: "RSS Read", description: "Read RSS feeds", domain: "n8n.io" },
  rundeck: { name: "Rundeck", description: "Runbook automation", domain: "rundeck.com" },
  s3: { name: "S3 (AWS S3)", description: "Object storage service", domain: "aws.amazon.com" },
  seatable: { name: "SeaTable", description: "Spreadsheet-database hybrid", domain: "seatable.io" },
  scrapfly: { name: "Scrapfly", description: "Web scraping API", domain: "scrapfly.io" },
  segment: { name: "Segment", description: "Customer data platform", domain: "segment.com" },
  sendemail: { name: "Send Email", description: "Send emails", domain: "n8n.io" },
  sendgrid: { name: "SendGrid", description: "Email delivery service", domain: "sendgrid.com" },
  sendy: { name: "Sendy", description: "Self-hosted email newsletter application", domain: "sendy.co" },
  sentimentanalysis: { name: "Sentiment Analysis", description: "Analyze text sentiment", domain: "n8n.io" },
  sentryio: { name: "Sentry.io", description: "Error tracking and performance monitoring", domain: "sentry.io" },
  servicenow: { name: "ServiceNow", description: "IT service management", domain: "servicenow.com" },
  serpapi: { name: "SerpApi", description: "Google Search API", domain: "serpapi.com" },
  seven: { name: "Seven", description: "Business messaging solutions", domain: "seven.io" },
  signl4: { name: "SIGNL4", description: "Mobile alerting and incident management", domain: "signl4.com" },
  slack: { name: "Slack", description: "Collaboration hub", domain: "slack.com" },
  snowflake: { name: "Snowflake", description: "Cloud data platform", domain: "snowflake.com" },
  sort: { name: "Sort", description: "Sort data", domain: "n8n.io" },
  spontit: { name: "Spontit", description: "Push notification service", domain: "spontit.com" },
  spreadsheetfile: { name: "Spreadsheet File (XLS, CSV)", description: "Work with spreadsheet files", domain: "n8n.io" },
  ssh: { name: "SSH", description: "Secure Shell protocol", domain: "ssh.com" },
  stackby: { name: "Stackby", description: "Spreadsheet-database hybrid", domain: "stackby.com" },
  stopanderror: { name: "Stop And Error", description: "Stop and handle errors", domain: "n8n.io" },
  storyblok: { name: "Storyblok", description: "Headless CMS", domain: "storyblok.com" },
  storm: { name: "Storm (Bankerize FGTS)", description: "Financial services platform", domain: "bankerize.com.br" },
  strapi: { name: "Strapi", description: "Open-source headless CMS", domain: "strapi.io" },
  strava: { name: "Strava", description: "Social network for athletes", domain: "strava.com" },
  stripe: { name: "Stripe", description: "Online payment processing", domain: "stripe.com" },
  stt: { name: "STT (Speech-to-Text)", description: "Convert speech to text", domain: "n8n.io" },
  substack: { name: "Substack", description: "Publishing platform", domain: "substack.com" },
  summarizationchain: { name: "Summarization Chain", description: "Summarize text", domain: "n8n.io" },
  syncromsp: { name: "SyncroMSP", description: "MSP platform for IT professionals", domain: "syncromsp.com" },
  taiga: { name: "Taiga", description: "Project management for agile developers", domain: "taiga.io" },
  tapfiliate: { name: "Tapfiliate", description: "Affiliate tracking software", domain: "tapfiliate.com" },
  telegram: { name: "Telegram", description: "Messaging app", domain: "telegram.org" },
  textmanipulation: { name: "Text Manipulation", description: "Manipulate text", domain: "n8n.io" },
  thehive: { name: "TheHive", description: "Security incident response platform", domain: "thehive-project.org" },
  thehive5: { name: "TheHive 5", description: "Security incident response platform", domain: "thehive-project.org" },
  tavily: { name: "Tavily", description: "AI-powered search API", domain: "tavily.com" },
  timescaledb: { name: "TimescaleDB", description: "Time-series SQL database", domain: "timescale.com" },
  tinyerp: { name: "Tiny ERP", description: "ERP for small businesses", domain: "tiny.com.br" },
  todoist: { name: "Todoist", description: "Task management app", domain: "todoist.com" },
  trello: { name: "Trello", description: "Collaboration tool", domain: "trello.com" },
  twake: { name: "Twake", description: "Team collaboration platform", domain: "twake.app" },
  twilio: { name: "Twilio", description: "Cloud communications platform", domain: "twilio.com" },
  twist: { name: "Twist", description: "Team communication app", domain: "twist.com" },
  typeform: { name: "Typeform", description: "Online form builder", domain: "typeform.com" },
  urlscanio: { name: "URLScan.io", description: "Website scanner for suspicious URLs", domain: "urlscan.io" },
  unleashedsoftware: { name: "Unleashed Software", description: "Inventory management software", domain: "unleashedsoftware.com" },
  uplead: { name: "UpLead", description: "B2B prospecting platform", domain: "uplead.com" },
  uproc: { name: "uProc", description: "Data enrichment and validation", domain: "uproc.io" },
  uptimerobot: { name: "UptimeRobot", description: "Website monitoring service", domain: "uptimerobot.com" },
  venafitlsprotectcloud: { name: "Venafi TLS Protect Cloud", description: "Machine identity management", domain: "venafi.com" },
  venafitlsprotectdatacenter: { name: "Venafi TLS Protect Datacenter", description: "Machine identity management", domain: "venafi.com" },
  vonage: { name: "Vonage", description: "Cloud communications platform", domain: "vonage.com" },
  webexbycisco: { name: "Webex by Cisco", description: "Video conferencing and messaging", domain: "webex.com" },
  webflow: { name: "Webflow", description: "Website builder", domain: "webflow.com" },
  wedof: { name: "Wedof", description: "E-learning platform", domain: "wedof.fr" },
  wekan: { name: "Wekan", description: "Open-source kanban board", domain: "wekan.fi" },
  whatsappbusinessaccount: { name: "WhatsApp Business Account", description: "Business messaging", domain: "whatsapp.com" },
  whatsappbusinesscloud: { name: "WhatsApp Business Cloud", description: "Cloud-hosted WhatsApp Business API", domain: "whatsapp.com" },
  wise: { name: "Wise", description: "Online money transfer service", domain: "wise.com" },
  woocommerce: { name: "WooCommerce", description: "E-commerce platform for WordPress", domain: "woocommerce.com" },
  wordpress: { name: "WordPress", description: "Content management system", domain: "wordpress.com" },
  x: { name: "X (Twitter API)", description: "Social networking service", domain: "twitter.com" },
  xata: { name: "Xata", description: "Serverless data platform", domain: "xata.io" },
  youtube: { name: "YouTube", description: "Online video sharing platform", domain: "youtube.com" },
  zalo: { name: "Zalo", description: "Messaging application", domain: "zalo.me" },
  zammad: { name: "Zammad", description: "Open source helpdesk and support system", domain: "zammad.com" },
  zep: { name: "Zep", description: "Long-term memory for AI assistants", domain: "getzep.com" },
  zendesk: { name: "Zendesk", description: "Customer service software", domain: "zendesk.com" },
  zohocrm: { name: "Zoho CRM", description: "Customer relationship management", domain: "zoho.com" },
  zoom: { name: "Zoom", description: "Video conferencing service", domain: "zoom.us" },
  zulip: { name: "Zulip", description: "Team chat application", domain: "zulip.com" },
};

export const integrationCategories: Record<string, { label: string; integrations: string[] }> = {
  "crm-sales": {
    label: "💼 CRM & Sales",
    integrations: ["advbox", "agilecrm", "asaas", "bamboohr", "bitrix24", "copper", "crmgestorclientes", "customerio", "freshworkscrm", "halopsa", "helpscout", "highlevel", "hubspot", "keap", "lonescale", "microsoftdynamicscrm", "monicacrm", "odoo", "pipedrive", "salesforce", "syncromsp", "tinyerp", "uplead", "zohocrm"],
  },
  communication: {
    label: "💬 Communication",
    integrations: ["actionnetwork", "discord", "egoi", "gmail", "line", "mailerlite", "mailgun", "mailjet", "matrix", "mattermost", "microsoftoutlook", "microsoftteams", "msg91", "pushbullet", "pushcut", "pushover", "sendgrid", "seven", "signl4", "slack", "telegram", "twilio", "twist", "whatsappbusinessaccount", "whatsappbusinesscloud", "zulip"],
  },
  "developer-tools": {
    label: "🛠️ Developer Tools",
    integrations: ["airbyte", "amqpsender", "apitemplateio", "awscognito", "awscomprehend", "awsdynamodb", "awselasticloadbalancing", "awslambda", "awsrekognition", "awss3", "awsses", "awssns", "awssqs", "awstextract", "awstranscribe", "azurecosmosdb", "azureopenai", "azurestorage", "brandfetch", "cnjplookup", "convertapi", "cortex", "crawler", "duckdb", "elasticsearch", "elasticsecurity", "evolutionapi", "facebookgraphapi", "firecrawl", "git", "github", "gitlab", "googlebigquery", "googlecloudfirestore", "googlecloudnaturallanguage", "googlecloudrealtimedatabase", "googlecloudstorage", "googleperspective", "jenkins", "jinaai", "kafka", "ldap", "merge", "microsoftentraid", "microsoftgraphsecurity", "microsoftsql", "minio", "mqtt", "mysql", "n8ninternal", "npm", "oauth2tinyerp", "okta", "oneapi", "onesimpleapi", "openai", "openthesaurus", "pdfkit", "peekalink", "perplexity", "postbin", "postgres", "rabbitmq", "redis", "rerankercohere", "rundeck", "s3", "scrapfly", "segment", "serpapi", "snowflake", "ssh", "stt", "summarizationchain", "tavily", "thehive", "thehive5", "timescaledb", "urlscanio", "venafitlsprotectcloud", "venafitlsprotectdatacenter", "xata", "zep"],
  },
  "project-management": {
    label: "📝 Project Management",
    integrations: ["appflowy", "asana", "baserow", "clickup", "filemaker", "flow", "grist", "jirasoftware", "linear", "mondaycom", "nocodb", "notion", "seatable", "stackby", "storyblok", "strapi", "taiga", "todoist", "trello", "wekan"],
  },
  marketing: {
    label: "📈 Marketing",
    integrations: ["bannerbear", "bitly", "brevo", "clearbit", "convertkit", "demio", "dropcontact", "getresponse", "googleads", "googleanalytics", "googlebusinessprofile", "hotmart", "humanticai", "hunter", "integremecnpj", "iterable", "keitaro", "lemlist", "mailchimp", "mautic", "posthog", "profitwell", "sendy", "substack", "tapfiliate", "uproc"],
  },
  "social-media": {
    label: "📱 Social Media",
    integrations: ["discourse", "disqus", "facebook", "instagram", "linkedin", "medium", "spontit", "strava", "x", "youtube", "zalo"],
  },
  "e-commerce": {
    label: "🛒 E-commerce",
    integrations: ["comerciaio", "paddle", "paypal", "stripe", "woocommerce", "wise"],
  },
  "file-management": {
    label: "📂 File Management",
    integrations: ["box", "dropbox", "googledocs", "googledrive", "googlesheets", "googleslides", "microsoftonedrive", "microsoftsharepoint", "raindrop"],
  },
  "lifestyle-health": {
    label: "🏃 Lifestyle & Health",
    integrations: ["beeminder", "homeassistant", "oura", "philipshue"],
  },
  "no-code": {
    label: "🤖 No-Code",
    integrations: ["adalo", "airtable", "bubble", "n8nform", "typeform", "webflow"],
  },
  utilities: {
    label: "⚙️ Utilities",
    integrations: ["calculator", "calcom", "carbonejs", "cloudconvert", "coingecko", "customerdatastore", "customermessenger", "datetime", "editimage", "editimageplus", "executiondata", "extractfromfile", "ftp", "gotowebinar", "hackernews", "mailcheck", "mineru", "nasa", "openweathermap", "phantombuster", "plivo", "randomizer", "rssread", "sendemail", "sentimentanalysis", "sentryio", "sort", "spreadsheetfile", "stopanderror", "textmanipulation", "unleashedsoftware", "uptimerobot", "vonage", "webexbycisco", "wedof"],
  },
};
