export const integrationData: Record<string, { name: string; description: string; slug: string }> = {
  hubspot: { name: "HubSpot", description: "Complete CRM with lead scoring, deal tracking, and email automation", slug: "hubspot" },
  salesforce: { name: "Salesforce", description: "Enterprise CRM with advanced pipeline management", slug: "salesforce" },
  pipedrive: { name: "Pipedrive", description: "Visual sales pipeline management", slug: "pipedrive" },
  zohocrm: { name: "Zoho CRM", description: "All-in-one customer relationship management", slug: "zoho" },
  freshsales: { name: "Freshsales", description: "Modern CRM with built-in phone and email", slug: "freshworks" },
  activecampaign: { name: "ActiveCampaign", description: "Email marketing with CRM capabilities", slug: "activecampaign" },
  copper: { name: "Copper", description: "CRM designed for Google Workspace", slug: "copper" },
  airtable: { name: "Airtable", description: "Spreadsheet-database hybrid for lead tracking", slug: "airtable" },
  notion: { name: "Notion", description: "All-in-one workspace for notes and docs", slug: "notion" },
  clickup: { name: "ClickUp", description: "Project management with CRM features", slug: "clickup" },
  monday: { name: "Monday.com", description: "Work OS for sales team collaboration", slug: "monday" },
  intercom: { name: "Intercom", description: "Customer messaging and support platform", slug: "intercom" },
  zendesk: { name: "Zendesk", description: "Customer service and ticketing system", slug: "zendesk" },
  calendly: { name: "Calendly", description: "Automated meeting scheduling", slug: "calendly" },
  typeform: { name: "Typeform", description: "Interactive forms and surveys", slug: "typeform" },
  slack: { name: "Slack", description: "Team messaging and collaboration hub", slug: "slack" },
  msteams: { name: "Microsoft Teams", description: "Video conferencing and team chat", slug: "microsoftteams" },
  discord: { name: "Discord", description: "Voice, video, and text communication", slug: "discord" },
  gmail: { name: "Gmail", description: "Email with advanced automation", slug: "gmail" },
  outlook: { name: "Outlook", description: "Microsoft email and calendar", slug: "microsoftoutlook" },
  twilio: { name: "Twilio", description: "SMS, voice, and video APIs", slug: "twilio" },
  zoom: { name: "Zoom", description: "Video conferencing and webinars", slug: "zoom" },
  quickbooks: { name: "QuickBooks", description: "Small business accounting software", slug: "quickbooks" },
  xero: { name: "Xero", description: "Cloud-based accounting platform", slug: "xero" },
  stripe: { name: "Stripe", description: "Online payment processing", slug: "stripe" },
  paypal: { name: "PayPal", description: "Digital payments platform", slug: "paypal" },
  googleanalytics: { name: "Google Analytics", description: "Website traffic and behavior analysis", slug: "googleanalytics" },
  googleads: { name: "Google Ads", description: "Online advertising platform", slug: "googleads" },
  facebookads: { name: "Facebook Ads", description: "Social media advertising", slug: "facebook" },
  mailchimp: { name: "Mailchimp", description: "Email marketing automation", slug: "mailchimp" },
  klaviyo: { name: "Klaviyo", description: "E-commerce email and SMS marketing", slug: "klaviyo" },
  googleworkspace: { name: "Google Workspace", description: "Gmail, Drive, Docs, Sheets, Calendar suite", slug: "google" },
  microsoft365: { name: "Microsoft 365", description: "Office apps and cloud services", slug: "microsoftoffice" },
  trello: { name: "Trello", description: "Visual project management boards", slug: "trello" },
  asana: { name: "Asana", description: "Team project and task management", slug: "asana" },
  shopify: { name: "Shopify", description: "Leading e-commerce platform", slug: "shopify" },
  woocommerce: { name: "WooCommerce", description: "WordPress e-commerce plugin", slug: "woocommerce" },
  magento: { name: "Magento", description: "Open source e-commerce platform", slug: "magento" },
  bigcommerce: { name: "BigCommerce", description: "Enterprise e-commerce solution", slug: "bigcommerce" },
  amazonsellercentral: { name: "Amazon Seller Central", description: "Amazon marketplace management", slug: "amazon" },
  openai: { name: "OpenAI", description: "GPT models for text and image generation", slug: "openai" },
  anthropic: { name: "Anthropic Claude", description: "AI assistant for conversations and analysis", slug: "anthropic" },
  googleai: { name: "Google AI", description: "Machine learning and AI services", slug: "google" },
  huggingface: { name: "Hugging Face", description: "Open source AI model platform", slug: "huggingface" },
  snowflake: { name: "Snowflake", description: "Cloud data warehouse", slug: "snowflake" },
  googledrive: { name: "Google Drive", description: "Cloud storage and file sharing", slug: "googledrive" },
  dropbox: { name: "Dropbox", description: "Cloud storage and collaboration", slug: "dropbox" },
  onedrive: { name: "OneDrive", description: "Microsoft cloud storage", slug: "onedrive" },
  s3: { name: "Amazon S3", description: "Object storage service", slug: "amazons3" },
  facebook: { name: "Facebook", description: "Social networking and business pages", slug: "facebook" },
  instagram: { name: "Instagram", description: "Photo and video sharing", slug: "instagram" },
  twitter: { name: "Twitter/X", description: "Microblogging and social networking", slug: "x" },
  linkedin: { name: "LinkedIn", description: "Professional networking", slug: "linkedin" },
  youtube: { name: "YouTube", description: "Video sharing platform", slug: "youtube" },
  httprequest: { name: "HTTP Request", description: "Connect to any REST API endpoint", slug: "webrequest" },
  webhooks: { name: "Webhooks", description: "Real-time HTTP callbacks", slug: "webhook" },
  graphql: { name: "GraphQL", description: "Query language for APIs", slug: "graphql" },
  python: { name: "Custom Python", description: "Execute custom Python code", slug: "python" },
  javascript: { name: "Custom JavaScript", description: "Run custom JavaScript functions", slug: "javascript" },
};

export const integrationCategories: Record<string, { label: string; integrations: string[] }> = {
  "crm-sales": {
    label: "💼 CRM & Sales",
    integrations: ["hubspot", "salesforce", "pipedrive", "zohocrm", "freshsales", "activecampaign", "copper", "airtable", "notion", "clickup", "monday", "intercom", "zendesk", "calendly", "typeform"],
  },
  communication: {
    label: "💬 Communication",
    integrations: ["slack", "msteams", "discord", "gmail", "outlook", "twilio", "zoom"],
  },
  finance: {
    label: "💰 Finance & Accounting",
    integrations: ["quickbooks", "xero", "stripe", "paypal"],
  },
  marketing: {
    label: "📈 Marketing",
    integrations: ["googleanalytics", "googleads", "facebookads", "mailchimp", "klaviyo"],
  },
  productivity: {
    label: "⚡ Productivity",
    integrations: ["googleworkspace", "microsoft365", "notion", "airtable", "trello", "asana", "monday", "clickup"],
  },
  ecommerce: {
    label: "🛒 E-commerce",
    integrations: ["shopify", "woocommerce", "magento", "bigcommerce", "amazonsellercentral"],
  },
  "ai-data": {
    label: "🤖 AI & Analytics",
    integrations: ["openai", "anthropic", "googleai", "huggingface", "snowflake"],
  },
  storage: {
    label: "☁️ Storage & Files",
    integrations: ["googledrive", "dropbox", "onedrive", "s3"],
  },
  social: {
    label: "📱 Social Media",
    integrations: ["facebook", "instagram", "twitter", "linkedin", "youtube"],
  },
  custom: {
    label: "🔧 Custom APIs",
    integrations: ["httprequest", "webhooks", "graphql", "python", "javascript"],
  },
};
